# -*- coding: utf-8 -*-
"""agente teste ra

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jWRq-Z9QIH4X2kQqRS9g9pYyvi41LwUC
"""

from google.colab import userdata
userdata.get('GOOGLE_API_KEY')

# prompt: fazendo com o agente consiga pesquisa no google quando for pedido

def execute_tool(response):
    # In a real scenario, this function would interact with a Google Search API.
    # For this simulation, we just print that a search is requested and return a placeholder result.
    print("Tool call requested (simulated): Google Search")
    # Simulate a tool call result. Replace with actual API call if available.
    # Example:
    # from google.colab import search
    # results = search.search(response.tool_calls[0].args['query'])
    # return results
    return "Tool execution result (simulated): Information found."

prompt = input("me fale seu problema 💔...")
while prompt != "Arrombados":
    response = chat.send_message(prompt)
    # Check if the model requested a tool call
    if hasattr(response, 'tool_calls') and response.tool_calls:
        tool_result = execute_tool(response)
        # Send the tool output back to the model
        response = chat.send_message(types.ToolOutput(tool_code=response.tool_calls[0].tool_code, contents=[types.Part(text=tool_result)]))
        print("respostas", response.text)
    else:
        print("respostas", response.text)
    print("\n\n")
    prompt = input("me fale seu problema 💔...")